# Generated by Django 4.1 on 2023-08-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehiclemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehiclenumber', models.CharField(max_length=10)),
                ('Vehicletype', models.CharField(choices=[('two', 'two'), ('three', 'three'), ('four', 'four')], max_length=30)),
                ('vehiclemodel', models.CharField(max_length=30)),
                ('vehicledesc', models.CharField(max_length=90)),
            ],
        ),
    ]
